import type { AppSnapshot } from "@/adapters/types"

export const mockDashboardSnapshot: AppSnapshot = {
  generated_at: "2026-06-20T14:18:00Z",
  generated_at_display: "2026-06-20T14:18:00Z",
  session: {
    commander: "Local Commander",
    ship: "Krait Mk II",
    system: "Sanitized System",
    mode: "Solo",
    active: true,
    status_label: "Active",
    started_at: "2026-06-20T13:36:00Z",
    started_at_display: "2026-06-20T13:36:00Z",
    ended_at: null,
    ended_at_display: null,
    elapsed_seconds: 2520,
    elapsed_display: "42m",
    shields_up: true,
    shields_display: "Up",
    ship_hull_percent: 0.92,
    ship_hull_display: "92%",
    fighter_hull_percent: 0.76,
    fighter_hull_display: "76%",
    fighter_alive: true,
    kills: 18,
    scans: 6,
    bounty_total: {
      value: 4_218_450,
      display: "4,218,450 cr",
    },
    merits: 12,
    merits_to_report: 3,
    kill_total_rate_per_hour: {
      value: 25.7,
      display: "25.7/h",
    },
    kill_recent_rate_per_hour: {
      value: 31.2,
      display: "31.2/h",
    },
    scan_total_rate_per_hour: {
      value: 8.6,
      display: "8.6/h",
    },
    scan_recent_rate_per_hour: {
      value: 7.9,
      display: "7.9/h",
    },
    last_kill_at: "2026-06-20T14:11:19Z",
    last_kill_display: "2026-06-20T14:11:19Z",
    last_scan_at: "2026-06-20T14:08:33Z",
    last_scan_display: "2026-06-20T14:08:33Z",
  },
  missions: {
    active_count: 2,
    completed_count: 1,
    total_count: 3,
    status_label: "2",
    items: [
      {
        mission_id: 410024,
        state: "active",
        state_label: "Active",
        kind: "massacre",
        kind_label: "Massacre",
        display_name: "Massacre pirates",
        issuing_faction: "Sanitized Resistance",
        target_faction: "Sanitized Raiders",
        destination_system: "Sanitized System",
        destination_station: "Sanitized Station",
        accepted_at: "2026-06-20T13:20:00Z",
        accepted_at_display: "2026-06-20T13:20:00Z",
        expiry: "2026-06-20T19:20:00Z",
        expiry_display: "2026-06-20T19:20:00Z",
        reward: {
          value: 5_820_000,
          display: "5,820,000 cr",
        },
        progress: {
          kind: "massacre",
          target: "Pirates",
          target_faction: "Sanitized Raiders",
          kills: 24,
          kill_count: 36,
          display: "24/36 kills",
        },
      },
      {
        mission_id: 410031,
        state: "active",
        state_label: "Active",
        kind: "massacre",
        kind_label: "Massacre",
        display_name: "Suppress hostile wing",
        issuing_faction: "Sanitized Security",
        target_faction: "Sanitized Raiders",
        destination_system: "Sanitized System",
        destination_station: null,
        accepted_at: "2026-06-20T13:44:00Z",
        accepted_at_display: "2026-06-20T13:44:00Z",
        expiry: "2026-06-20T20:44:00Z",
        expiry_display: "2026-06-20T20:44:00Z",
        reward: {
          value: 2_450_000,
          display: "2,450,000 cr",
        },
        progress: {
          kind: "massacre",
          target: "Pirates",
          target_faction: "Sanitized Raiders",
          kills: 8,
          kill_count: 12,
          display: "8/12 kills",
        },
      },
    ],
  },
  afk_checklist: {
    rows: [
      {
        id: "hardpoints_deployed",
        label: "Hardpoints deployed",
        detail: "Status Flags bit 0x40 is set",
        state: "pass",
        source: "Status.json",
      },
      {
        id: "engine_pips_zero",
        label: "Engine pips zero",
        detail: "Status Pips[1] is 0",
        state: "pass",
        source: "Status.json",
      },
      {
        id: "cargo_loaded",
        label: "Cargo loaded",
        detail: "Cargo.json Ship cargo is non-empty",
        state: "fail",
        source: "Cargo.json",
      },
    ],
  },
  notifications: [
    {
      event_type: "kill",
      level: 1,
      alert_level: "info",
      emoji: null,
      text: "Bounty voucher recorded; counters updated",
      timestamp: "2026-06-20T14:11:19Z",
      timestamp_display: "2026-06-20T14:11:19Z",
      mention: false,
    },
  ],
  event_feed: [
    {
      id: "mock-event-004",
      source: "notification",
      event_type: "kill",
      level: 1,
      summary: "Bounty voucher recorded; counters updated",
      timestamp: "2026-06-20T14:11:19Z",
      timestamp_display: "14:11:19",
    },
    {
      id: "mock-event-003",
      source: "notification",
      event_type: "mission",
      level: 2,
      summary: "Mission progress advanced to 24/36 kills",
      timestamp: "2026-06-20T14:10:04Z",
      timestamp_display: "14:10:04",
    },
    {
      id: "mock-event-002",
      source: "notification",
      event_type: "scan",
      level: 1,
      summary: "Cargo scan count increased",
      timestamp: "2026-06-20T14:08:33Z",
      timestamp_display: "14:08:33",
    },
    {
      id: "mock-event-001",
      source: "lifecycle",
      event_type: "journal_source",
      level: 0,
      summary: "Sanitized Journal source selected for mock runtime",
      timestamp: "2026-06-20T13:36:00Z",
      timestamp_display: "13:36:00",
    },
  ],
  journal_source: {
    folder: "Sanitized Journal source",
    selected_file: "Journal.sanitized.01.log",
    recent_files: 3,
    status_label: "Running",
  },
  matrix: {
    kind: "disabled",
    status_label: "Disabled",
    message: "No token exposed in mock mode",
    room_id: null,
    bind_address: null,
    url: null,
    checked_at: null,
    checked_at_display: null,
  },
  web: {
    kind: "running",
    status_label: "Mock live",
    message: "No production API configured",
    room_id: null,
    bind_address: "mock-adapter",
    url: null,
    checked_at: "2026-06-20T14:18:00Z",
    checked_at_display: "2026-06-20T14:18:00Z",
  },
  tunnel: {
    kind: "start",
    status_label: "Start",
    provider: "cloudflare_quick",
    provider_label: "Cloudflare Quick Tunnel",
    session_id: null,
    message: null,
    public_url: null,
    checked_at: "2026-06-20T14:18:00Z",
    checked_at_display: "2026-06-20T14:18:00Z",
    retryable_error: false,
  },
}
